#!/usr/bin/env python

import sys
import math

if len(sys.argv) != 4:
    raise Exception('Podałeś złą liczbę argumentów.')
a = sys.argv[1]
b = sys.argv[2]
c = sys.argv[3]


def funkcja(a, b, c):
    boki = sorted([a, b, c])
    a = int(boki[0])
    b = int(boki[1])
    c = int(boki[2])
    if not a + b >= c:
        raise ValueError('To nie jest trójkąt.')
    print(a, b, c)
    print('Obwód trójkąta:', a + b + c)
    p = (a + b + c) / 2
    print('Pole trójkąta:', math.sqrt(p * (p - a) * (p - b) * (p - c)))
    if a == b and b == c and a == c:
        print('Równoboczny')
    if a == b or a==c or b==c:
        print('Równoramienny')
    else:
        print('Różnoboczny')
    z = a ** 2 + b ** 2 - c ** 2
    if z == 0:
        print('Prostokątny')
    if z > 0:
        print('Rozwartokątny')
    else:
        print('Ostrokatny')


funkcja(a, b, c)
